# Generated by Django 5.2.8 on 2025-11-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options_category_created_at_and_more'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم الدواء (عربي)')),
                ('name_english', models.CharField(blank=True, max_length=300, null=True, verbose_name='اسم الدواء (إنجليزي)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('strength', models.CharField(blank=True, max_length=100, null=True, verbose_name='التركيز')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة الدواء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('views', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('clicks', models.IntegerField(default=0, verbose_name='عدد النقرات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='الفئة')),
                ('pharmacies', models.ManyToManyField(blank=True, related_name='products', to='pharmacies.pharmacy', verbose_name='الصيدليات المتوفرة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
    ]
