# Generated by Django 5.2.8 on 2025-11-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='اللون')),
                ('views', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'فئة الأدوية',
                'verbose_name_plural': 'فئات الأدوية',
            },
        ),
    ]
