# Generated by Django 5.2.8 on 2025-11-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصيدلية')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='الموقع')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharmacies/', verbose_name='صورة الصيدلية')),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3, verbose_name='التقييم')),
                ('rating_count', models.IntegerField(default=0, verbose_name='عدد التقييمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
